Yaumi-Digital-School/quranplus-flutter

- lib/pages/home_page_v2/home_page_state_notifier.dart
- lib/pages/tadabbur_surah_list_page/tadabbur_surah_list_view_state_notifier.dart
- lib/shared/core/services/tadabbur_service.dart
Previously, there was an issue where some users were getting stuck on the splash screen. After investigating, I found that this was due to users being connected to the internet but having a poor internet speed. In this PR, I attempt to fix this bug.
> [Fix] Stuck on Splash Screen

- lib/widgets/change_theme_bottom_sheet.dart
- lib/widgets/theme_box_option_widget.dart
Add name theme on checkbox change theme
- Login
- Pin
- Homepage
- etc
> [Feature] Add Theme Information Checkbox

- ios/Podfile.lock
- lib/pages/bookmark_page.dart
- lib/pages/habit_page/habit_progress/widgets/add_daily_progress_manual/add_daily_progress_manual_view.dart
- lib/pages/habit_page/habit_progress/widgets/change_daily_target/change_daily_target_view.dart
- lib/pages/habit_page/habit_progress/widgets/habit_personal/habit_personal_view.dart
- lib/pages/splash_page/splash_page.dart
- lib/pages/surat_page_v3/surat_page_v3.dart
- lib/pages/surat_page_v3/widgets/post_tracking_dialog.dart
- lib/pages/surat_page_v3/widgets/submission_dialog.dart
- lib/pages/surat_page_v3/widgets/surat_page_settings_drawer.dart
- lib/widgets/alert_dialog.dart
- lib/widgets/utils/general_dialog.dart
Add theme configuration for dialog and surat page sidebar drawer
- surat page
- all pages that have dialog in it
Tested locally
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36220334/5fcabf08-bce9-4503-a8ca-4eaf4b792841
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36220334/12879641-c993-49df-aedb-e927efe57d83
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36220334/dc0cae3b-365f-459e-b307-1dff75ecd380
> [Feature] implement color theme on dialog

- lib/pages/account_deletion/account_deletion_view.dart
- lib/pages/settings_page/settings_page.dart
- lib/pages/settings_page/widgets/version_app_widget.dart
- lib/pages/surat_page_v3/surat_page_v3.dart
- lib/pages/surat_page_v3/widgets/surat_page_settings_drawer.dart
- lib/shared/constants/qp_theme_data.dart
- lib/shared/core/models/theme_option_color_param.dart
- lib/shared/core/providers.dart
- lib/shared/core/state_notifiers/theme_state_notifier.dart
- lib/widgets/app_update/force_update_dialog.dart
- lib/widgets/app_update/optional_update_dialog.dart
- lib/widgets/change_theme_bottom_sheet.dart
- lib/widgets/theme_box_option_widget.dart
- pubspec.yaml
Add select theme capability from reading quran page
- Surat/reading quran page
Tested locally in release & debug mode
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36220334/200aa28c-1f1d-4d60-b9f8-71a6790eb38c
> feat: implement select theme on reading page

- lib/shared/constants/qp_text_style.dart
- lib/widgets/general_bottom_sheet.dart
Implement theming functionality in no internet bottom sheet
- no internet bottom sheet on general_bottom_sheet widget
check on impacted widget
> [Feature] implement color theme on no internet bottom sheet

- lib/pages/surat_page_v3/surat_page_state_notifier.dart
- lib/pages/surat_page_v3/surat_page_v3.dart
- Login
- Pin
- Homepage
- etc
> fix: missing handler on separator builder

- lib/pages/surat_page_v3/surat_page_v3.dart
- pubspec.yaml
- Login
- Pin
- Homepage
- etc
> chore: build 77

- lib/pages/home_page_v2/home_page_v2.dart
- lib/pages/surat_page_v3/surat_page_v3.dart
- lib/shared/core/apis/audio_api.dart
- lib/shared/core/apis/model/audio.dart
- lib/shared/core/providers.dart
- lib/shared/core/providers/audio_provider.dart
- lib/widgets/audio_bottom_sheet/audio_bottom_sheet_state_notifier.dart
- lib/widgets/audio_bottom_sheet/audio_bottom_sheet_widget.dart
In this pull request, I added functionality to hit an audio URL and play the audio based on the obtained audio URL. I also added auto-play when the audio finishes loading.
Preview:
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36232396/47fb477d-6b6b-4750-8e2c-606bc20c023c
> feat: api audio integration

- lib/pages/surat_page_v3/surat_page_v3.dart
- lib/widgets/audio_bottom_sheet/audio_bottom_sheet_state_notifier.dart
In this PR, I added a CTA (Call to Action) to play audio from the app bar. The audio being played corresponds to the first verse pointed out on a page of the Quran.
trello task: https://trello.com/c/z7n3zTdY/167-as-a-user-i-want-to-be-able-to-play-the-audio-for-the-whole-surah-so-that-i-can-listen-to-the-audio-for-all-verses-from-that-sur
Preview:
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36232396/1fc484d0-77e7-4994-ac8a-38f8cd9474cc
- Login
- Pin
- Homepage
- etc
> feat: play audio on top appbar cta

- lib/shared/core/apis/model/audio.dart
- lib/shared/core/services/shared_preference_service.dart
fix typo on fromjson that makes retrofit produces an error
> fix: typo on fromjson

- lib/pages/surat_page_v3/surat_page_v3.dart
- lib/shared/core/providers/audio_provider.dart
- lib/shared/core/services/audio_recitation/audio_recitation_handler.dart
- lib/widgets/audio_bottom_sheet/Select_Reciter_state_notifier.dart
- lib/widgets/audio_bottom_sheet/audio_bottom_sheet_widget.dart
- lib/widgets/audio_bottom_sheet/audio_recitation_state_notifier.dart
- lib/widgets/audio_bottom_sheet/radio_button_change_reciter.dart
- lib/widgets/audio_bottom_sheet/select_reciter_buttom_sheet.dart
- lib/widgets/general_bottom_sheet.dart
Enable play and pause button on reciter previews
- Surat Page -> recitator selection bottom sheet
https://github.com/Yaumi-Digital-School/quranplus-flutter/assets/36220334/6163f74c-589d-41f3-ad89-41220207a0fa
> feat: enable play and pause button on reciter previews

- .github/workflows/bump_build.yml
- Login
- Pin
- Homepage
- etc
> feat: improve

- .github/workflows/bump_build.yml
- Login
- Pin
- Homepage
- etc
> fix: bump build missing dash

- .github/workflows/bump_build.yml
- Login
- Pin
- Homepage
- etc
> feat: improve bump build part 5

- .github/workflows/bump_build.yml
- Login
- Pin
- Homepage
- etc
> feat: improve bump build to use secret token

- lib/main.dart
- lib/pages/bookmark_v2/bookmark_page_v2.dart
- lib/pages/habit_page/habit_page.dart
- lib/pages/habit_page/habit_state_notifier.dart
- lib/pages/home_page_v2/home_page_state_notifier.dart
- lib/pages/home_page_v2/home_page_v2.dart
- lib/pages/prayer_time_page/prayer_times_notifier.dart
- lib/pages/settings_page/settings_page.dart
- lib/pages/surat_page_v3/surat_page_v3.dart
- lib/widgets/general_bottom_sheet.dart
Revamp homepage with new design: https://www.figma.com/file/EYWLwgRYAdbPRfcIHeioXl/Apps-Quran-PLUS?node-id=8077%3A49143&mode=dev
preview:
- Login
- Pin
- Homepage
- etc
> feat: revamp homepage

- lib/shared/utils/prayer_times.dart
- Login
- Pin
- Homepage
- etc
> fix: replace 30 seconds to minutes

- lib/pages/splash_page/splash_page.dart
- lib/shared/core/services/shared_preference_service.dart
- Login
- Pin
- Homepage
- etc
> fix: replace set notif condition

- lib/pages/splash_page/splash_page.dart
- Login
- Pin
- Homepage
- etc
> fix: false date format

- lib/pages/home_page_v2/home_page_v2.dart
- lib/pages/home_page_v2/widgets/card_start_habit.dart
- lib/pages/home_page_v2/widgets/daily_progress_tracker_detail_card/daily_progress_tracker_detail_card.dart
- lib/pages/splash_page/splash_page.dart
Fixing the card habit at homepage. 
- Login
- Pin
- Homepage
- etc
> fix: change habit card on homepage
